name: Compile Binaries

on:
  workflow_dispatch:
  #push:
    #branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows-x64:

    #runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build executable
      run: cargo build --release
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4

      with:
        name: ${{ github.job }}
        path: ./target/release/nightingale.exe
        compression-level: 0

  build-windows-x86:

    #runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x86
    
    - name: Build executable
      run: |
        rustup install stable-i686-pc-windows-msvc
        rustup target add i686-pc-windows-msvc
        rustup run stable-i686-pc-windows-msvc cargo build --release
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4

      with:
        name: ${{ github.job }}
        path: ./target/release/nightingale.exe
        compression-level: 0
            
      

