name: Compile Binaries

on:
  workflow_dispatch:
  #push:
    #branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows-x64:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build executable
      run: cargo build --release
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4

      with:
        name: ${{ github.job }}
        path: ./target/release/nightingale.exe
        compression-level: 0

  build-windows-x86:

    #runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install x86 toolchain
      run: |
        rustup install stable-i686-pc-windows-msvc
        rustup target add i686-pc-windows-msvc
    
    - name: Build executable
      run: rustup run stable-i686-pc-windows-msvc cargo build --release
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4

      with:
        name: ${{ github.job }}
        path: ./target/release/nightingale.exe
        compression-level: 0
        
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build executable
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}
          path: ./target/release/nightingale
          compression-level: 0

  build-linux-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install x86 toolchain
        run: |
          rustup install stable-i686-unknown-linux-gnu
          rustup target add i686-unknown-linux-gnu
      
      - name: Build executable
        run: rustup run stable-i686-unknown-linux-gnu cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}
          path: ./target/release/nightingale
          compression-level: 0
      

